In [4]:
%pip install numpy scipy control sympy

  Using cached control-0.10.2-py3-none-any.whl.metadata (7.6 kB)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Using cached control-0.10.2-py3-none-any.whl (578 kB)
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)

   ---------------------------------------- 0/3 [mpmath]
   ---------------------------------------- 0/3 [mpmath]
   ---------------------------------------- 0/3 [mpmath]
   ---------------------------------------- 0/3 [mpmath]
   ---------------------------------------- 0/3 [mpmath]
   ---------------------------------------- 0/3 [mpmath]
   ------------- -------------------------- 1/3 [sympy]
   ------------- -------------------------- 1/3 [sympy]
   ------------- -------------------------- 1/3 [sympy]
   ------------- -------------------------- 1/3 [sympy]
   ------------- -------------------------- 1/3 [sympy]
   ------------- ------------

In [5]:


import numpy as np 
import scipy.linalg as la



All the requriments and the codes are in single note book  task of hore work is splits into the cells one after another , questions will end up with some markdown txt as this . 

In [7]:
# define A,B,C matrices
A = np.array([[0,1,0,0],[0,0,1,0],[0,0,0,1],[-1,-6,-5,-4]], dtype=float)
B = np.array([[0],[0],[0],[1]], dtype=float)
C = np.array([[1,0,0,0]], dtype=float)

#a) compute garamian using lypunov equation 

Wc_lyap = la.solve_continuous_lyapunov(A, -B@B.T)
Wo_lyap = la.solve_continuous_lyapunov(A.T, -C.T@C)

#b )  Compute Controllability & Observability matrices and their ranks

# Controllability matrix C_mat = [B, AB, A^2 B, A^3 B]
C_mat = np.hstack([np.linalg.matrix_power(A, i) @ B for i in range(4)])

# Observability matrix O_mat = [C; CA; CA^2; CA^3]
O_mat = np.vstack([C @ np.linalg.matrix_power(A, i) for i in range(4)])

rank_C = np.linalg.matrix_rank(C_mat)
rank_O = np.linalg.matrix_rank(O_mat)

# # (c) Compute Gramians using control.gram (if control library is installed)
# =====================================================================
try:
    import control as ct
    sys = ct.ss(A, B, C, 0)
    Wc_gram = ct.gram(sys, 'c')
    Wo_gram = ct.gram(sys, 'o')
    control_installed = True
except ImportError:
    # Manual Gramian computation fallback matching control.gram behavior
    Wc_gram, Wo_gram = Wc_lyap, Wo_lyap
    control_installed = False

# results 
print("--- (a) Gramians via Lyapunov Equations ---")
print("Controllability Gramian (Wc):\n", np.round(Wc_lyap, 4))
print("\nObservability Gramian (Wo):\n", np.round(Wo_lyap, 4))

print("\n--- (b) Rank Verification ---")
print("Controllability Matrix C:\n", C_mat)
print(f"Rank(C) = {rank_C} (Full Rank: {rank_C == 4})")

print("\nObservability Matrix O:\n", O_mat)
print(f"Rank(O) = {rank_O} (Full Rank: {rank_O == 4})")

print("\n--- (c) Gramians via control.gram vs Lyapunov ---")
print("Wc matches lyap:", np.allclose(Wc_lyap, Wc_gram))
print("Wo matches lyap:", np.allclose(Wo_lyap, Wo_gram))

--- (a) Gramians via Lyapunov Equations ---
Controllability Gramian (Wc):
 [[ 0.1029 -0.     -0.0294 -0.    ]
 [-0.      0.0294 -0.     -0.0441]
 [-0.0294 -0.      0.0441  0.    ]
 [-0.     -0.0441  0.      0.1912]]

Observability Gramian (Wo):
 [[3.4853 2.9118 2.1029 0.5   ]
 [2.9118 2.7941 2.0588 0.4853]
 [2.1029 2.0588 1.6765 0.4118]
 [0.5    0.4853 0.4118 0.1029]]

--- (b) Rank Verification ---
Controllability Matrix C:
 [[  0.   0.   0.   1.]
 [  0.   0.   1.  -4.]
 [  0.   1.  -4.  11.]
 [  1.  -4.  11. -30.]]
Rank(C) = 4 (Full Rank: True)

Observability Matrix O:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Rank(O) = 4 (Full Rank: True)

--- (c) Gramians via control.gram vs Lyapunov ---
Wc matches lyap: True
Wo matches lyap: True
